### ISSUE TITLE
Tls settings for init users

### ISSUE THREAD

**Issue by NikolayMurha** [csuka/ansible_role_mongodb#1]
Hello. Thank you for good playbook.

How can I use TLS for users initialization. I run before your and generate tls certs for servers and modify nodes configs and users settings but I can't set tls settings for intialization

**Comment by csuka** [comment]
I don't know exactly what you mean, perhaps you can elaborate a bit on your use case?
Perhaps you can find the answer here: https://github.com/csuka/ansible_role_mongodb/blob/main/tasks/user.yml#L27

**Comment by NikolayMurha** [comment]
Hello. Thank you for your response. I mean these tasks: https://github.com/csuka/ansible_role_mongodb/blob/main/tasks/user_init.yml

**Comment by csuka** [comment]
Try configuring it after creation of users.
